---
resources:
  - name: pruefungsplaner-meta
    type: git
    source:
      uri: https://github.com/Zebreus/pruefungsplaner-meta.git
      branch: master
  - name: pruefungsplaner-datamodel
    type: git
    source:
      uri: https://github.com/Zebreus/pruefungsplaner-datamodel.git
      branch: master
  - name: pruefungsplaner-frontend
    type: git
    source:
      uri: https://github.com/Zebreus/pruefungsplaner.git
      branch: master
  - name: pruefungsplaner-scheduler
    type: git
    source:
      uri: https://github.com/Zebreus/pruefungsplaner-scheduler.git
      branch: master
  - name: pruefungsplaner-backend
    type: git
    source:
      uri: https://github.com/Zebreus/pruefungsplaner-backend.git
      branch: master
  - name: qt-webassembly
    type: registry-image
    source:
      repository: madmanfred/qt-webassembly
      tag: "qt5.15-em1.39.7"
  - name: pruefungsplaner-frontend-latest
    type: registry-image
    source:
      repository: ((registry_username))/pruefungsplaner-frontend
      username: ((registry_username))
      password: ((registry_password))
      tag: latest
  - name: pruefungsplaner-scheduler-latest
    type: registry-image
    source:
      repository: ((registry_username))/pruefungsplaner-scheduler
      username: ((registry_username))
      password: ((registry_password))
      tag: latest
  - name: pruefungsplaner-backend-latest
    type: registry-image
    source:
      repository: ((registry_username))/pruefungsplaner-backend
      username: ((registry_username))
      password: ((registry_password))
      tag: latest
  - name: qt5-builder
    type: registry-image
    source:
      repository: ((registry_username))/qt5-builder
      username: ((registry_username))
      password: ((registry_password))
      tag: latest      
  - name: oci-build-task
    type: registry-image
    source:
      repository: vito/oci-build-task

jobs:
  - name: build-qt5-builder
    public: true
    plan:
      - get: pruefungsplaner-meta
        trigger: true
      - get: oci-build-task
      - task: build-qt5
        privileged: true
        image: oci-build-task
        config:
          platform: linux
          params:
            DOCKERFILE: ./pruefungsplaner-meta/qt5-builder/Dockerfile
          inputs:
          - name: pruefungsplaner-meta
          outputs:
          - name: image
          caches:
          - path: cache
          run:
            path: build
      - put: qt5-builder
        params: {image: image/image.tar}
  - name: build-frontend-container
    public: false
    plan:
      - get: pruefungsplaner-frontend
        trigger: true
      - get: pruefungsplaner-meta
      - get: qt-webassembly
      - get: oci-build-task
      - task: build-frontend
        file: pruefungsplaner-frontend/concourse/task-build-wasm.yml
        image: qt-webassembly
        privileged: true
      - task: build-task-image
        privileged: true
        image: oci-build-task
        config:
          platform: linux
          inputs:
            - name: built-frontend
              path: frontend
              optional: false
            - name: pruefungsplaner-meta
              optional: false
          params:
            DOCKERFILE: ./pruefungsplaner-meta/frontend/Dockerfile
          outputs:
            - name: image
          caches:
            - path: cache
          run:
            path: build
      - put: pruefungsplaner-frontend-latest
        params:
          image: image/image.tar
  - name: test-datamodel
    public: false
    plan:
      - get: pruefungsplaner-datamodel
        trigger: true
      - get: qt5-builder
      - task: build-tests
        privileged: true
        file: pruefungsplaner-datamodel/concourse/task_build_tests.yml
        image: qt5-builder
      - task: run-tests
        privileged: true
        file: pruefungsplaner-datamodel/concourse/task_run_tests.yml
        image: qt5-builder
  - name: test-scheduler
    public: false
    plan:
      - get: pruefungsplaner-scheduler
        trigger: true
      - get: qt5-builder
      - task: build-tests
        privileged: true
        file: pruefungsplaner-scheduler/concourse/task_build_tests.yml
        image: qt5-builder
      - task: run-tests
        privileged: true
        file: pruefungsplaner-scheduler/concourse/task_run_tests.yml
        image: qt5-builder
  - name: build-scheduler-container
    public: false
    plan:
      - get: pruefungsplaner-scheduler
        passed: [test-scheduler]
        trigger: true
      - get: pruefungsplaner-meta
        trigger: true
      - get: qt5-builder
      - get: oci-build-task
      - task: build-scheduler
        file: pruefungsplaner-scheduler/concourse/task_build_scheduler.yml
        image: qt5-builder
        privileged: true
      - task: build-task-image
        privileged: true
        image: oci-build-task
        config:
          platform: linux
          inputs:
            - name: built-scheduler
              optional: false
            - name: pruefungsplaner-meta
              optional: false
          params:
            DOCKERFILE: ./pruefungsplaner-meta/scheduler/Dockerfile
          outputs:
            - name: image
          caches:
            - path: cache
          run:
            path: build
      - put: pruefungsplaner-scheduler-latest
        params:
          image: image/image.tar
  - name: test-backend
    public: false
    plan:
      - get: pruefungsplaner-backend
        trigger: true
      - get: qt5-builder
      - task: build-tests
        privileged: true
        file: pruefungsplaner-backend/concourse/task_build_tests.yml
        image: qt5-builder
      - task: run-tests
        privileged: true
        file: pruefungsplaner-backend/concourse/task_run_tests.yml
        image: qt5-builder
  - name: build-backend-container
    public: false
    plan:
      - get: pruefungsplaner-backend
        passed: [test-backend]
        trigger: true
      - get: pruefungsplaner-meta
        trigger: true
      - get: qt5-builder
      - get: oci-build-task
      - task: build-backend
        file: pruefungsplaner-backend/concourse/task_build.yml
        image: qt5-builder
        privileged: true
      - task: build-task-image
        privileged: true
        image: oci-build-task
        config:
          platform: linux
          inputs:
            - name: built-backend
              optional: false
            - name: pruefungsplaner-meta
              optional: false
          params:
            DOCKERFILE: ./pruefungsplaner-meta/backend/Dockerfile
          outputs:
            - name: image
          caches:
            - path: cache
          run:
            path: build
      - put: pruefungsplaner-backend-latest
        params:
          image: image/image.tar
