---
resources:
  - name: pruefungsplaner-meta
    type: git
    source:
      uri: https://github.com/Zebreus/pruefungsplaner-meta.git
      branch: master
  - name: pruefungsplaner-frontend
    type: git
    source:
      uri: https://github.com/Zebreus/pruefungsplaner.git
      branch: master
  - name: qt-webassembly
    type: registry-image
    source:
      repository: madmanfred/qt-webassembly
      tag: "qt5.15-em1.39.7"
  - name: pruefungsplaner-frontend-latest
    type: registry-image
    source:
      repository: ((registry_username))/pruefungsplaner-frontend
      username: ((registry_username))
      password: ((registry_password))
      tag: latest
  - name: qt5-builder
    type: registry-image
    source:
      repository: ((registry_username))/qt5-builder
      username: ((registry_username))
      password: ((registry_password))
      tag: latest      
  - name: oci-build-task
    type: registry-image
    source:
      repository: vito/oci-build-task


jobs:
  - name: build-qt5-builder
    public: true
    plan:
      - get: pruefungsplaner-meta
        trigger: true
      - get: oci-build-task
      - task: build-qt5
        privileged: true
        image: oci-build-task
        config:
          platform: linux
          params:
            DOCKERFILE: ./pruefungsplaner-meta/qt5-builder/Dockerfile
          inputs:
          - name: pruefungsplaner-meta
          outputs:
          - name: image
          caches:
          - path: cache
          run:
            path: build
      - put: qt5-builder
        params: {image: image/image.tar}
  - name: build-frontend-container
    public: false
    plan:
      - get: pruefungsplaner-frontend
        trigger: true
      - get: qt-webassembly
      - get: oci-build-task
      - task: build-frontend
        file: pruefungsplaner-frontend/concourse/task-build-wasm.yml
        image: qt-webassembly
        privileged: true
      - task: build-task-image
        privileged: true
        file: pruefungsplaner-frontend/concourse/task-build-container.yml
        image: oci-build-task
      - put: pruefungsplaner-frontend-latest
        params:
          image: image/image.tar
  
